### ISSUE TITLE
wrong deepspeed version?

### ISSUE THREAD

**Issue by libTorrentUser** [neonbjb/tortoise-tts#510]
Shouldn't the deepspeed version in the requirements be 0.9.0 (or something like that) instead of 9.0?

**Comment by manmay-nakhashi** [comment]
Fixed

**Comment by SinanAkkoyun** [comment]
How did you get it up and running with deepspeed? I had to downgrade torch to 1.13 etc and it still doesn't work
https://github.com/neonbjb/tortoise-tts/issues/573

**Comment by SinanAkkoyun** [comment]
(and @manmay-nakhashi is your fork still faster than the official repo or did you PR all changes?)

**Comment by manmay-nakhashi** [comment]
@SinanAkkoyun I have pushed most of the changes in main repo

**Comment by SinanAkkoyun** [comment]
Great, thank you for the work! How did you manage to install deepspeed? I am strugging with it

**Comment by manmay-nakhashi** [comment]
Install pytorch with conda install exact deepspeed version mentioned in requirements.txt and it should work.

**Comment by SinanAkkoyun** [comment]
What pytorch version? I've tried 1.13, 1.8 and 2.0 with conda and it resulted in:
```
Traceback (most recent call last):
  File "/home/ubuntu/ml/speech/tts/tortoise/tortoise-tts/tortoise/do_tts.py", line 44, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/ubuntu/ml/speech/tts/tortoise/tortoise-tts/tortoise/api.py", line 346, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/ubuntu/ml/speech/tts/tortoise/tortoise-tts/tortoise/api.py", line 430, in tts
    codes = autoregressive.inference_speech(auto_conditioning, text_tokens,
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/tortoise/models/autoregressive.py", line 538, in inference_speech
    gen = self.inference_model.generate(inputs, bos_token_id=self.start_mel_token, pad_token_id=self.stop_mel_token, eos_token_id=self.stop_mel_token,
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/tortoise/models/autoregressive.py", line 149, in forward
    transformer_outputs = self.transformer(
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 900, in forward
    outputs = block(
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 166, in forward
    target_dtype = torch.half if self.dtype == torch.int8 else self.dtype
  File "/home/ubuntu/.anaconda3/envs/tortoise/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DeepSpeedGPTInference' object has no attribute 'dtype'. Did you mean: 'type'?
```

**Comment by SinanAkkoyun** [comment]
Oh great it works! I installed 0.9.0 instead the one in requirements.txt. Thank you so much!
The speed is great, I get around 4 seconds for one sentence. Is that expected for a 3090 at ultra_fast and one candidate? Are you planning on optimizing to go sub-1 second? That would revolutionize the TTS world and make 11labs API redundant

**Comment by SinanAkkoyun** [comment]
Or is there a way to even further cut down the settings to make it achieve sub 1 second inference speeds?

**Comment by manmay-nakhashi** [comment]
not right now , maybe in the near future.

**Comment by SinanAkkoyun** [comment]
Awesome! Is there a way to support your work and do you know when you will approx. implement that?

**Comment by manmay-nakhashi** [comment]
I don't know, I do this in my free time, so it can take sometime to speed it up more (but it is possible).

**Comment by maximett123** [comment]
@SinanAkkoyun @manmay-nakhashi
I have the same problem when installing deepspeed, the latest version is deepspeed 0.8.3. on the requirements.txt. what should be the version of python and pytorch and conda?
