### ISSUE TITLE
NameError: name 'speaking_rate' is not defined

### ISSUE THREAD

**Issue by vsuPlayer** [neonbjb/tortoise-tts#538]
I couldn't find the reason for this error. I reinstalled many times but the result is the same. I don't know exactly which version of Python and Anaconda I should use. And I'm not sure what exactly should be in the requirements.txt file. Because a few tutorials write different things to the requirements.txt file. 

Commands I type from left to right:

conda create --name tortoise-tts python=3.9 , conda activate tortoise-tts , cd anaconda3 , pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 , conda install -c conda-forge pysoundfile , git clone https://github.com/neonbjb/tortoise-tts.git , cd tortoise-tts , python -m pip install -r ./requirements.txt , conda install numba , 
python setup.py install 

conda update -n base -c defaults conda < I wasn't sure if I should use this update command. 

Used requirements.txt file:

tqdm , rotary_embedding_torch , transformers==4.19 , tokenizers , inflect , progressbar , einops==0.4.1 , unidecode , scipy==1.10.1 , librosa==0.9.1 , ffmpeg , numpy==1.20.3 , torchaudio , threadpoolctl , appdirs

(tortoise-tts) D:\Voice\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "D:\Voice\tortoise-tts\tortoise\do_tts.py", line 38, in <module>
    gen, dbg_state = tts.tts_with_preset(args.text, speaking_rate=speaking_rate, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
NameError: name 'speaking_rate' is not defined

**Comment by manmay-nakhashi** [comment]
fixed

**Comment by vsuPlayer** [comment]
@manmay-nakhashi 
My problem is not solved, but you write fixed.

**Comment by manmay-nakhashi** [comment]
can you please do git pull ?

**Comment by vsuPlayer** [comment]
Yes, but I have to go to work now. I can when I come in the evening. Can you help?

**Comment by vsuPlayer** [comment]
I installed the latest version of everything and it works.
